# define a compiler
CC = gcc

# define location of header files
IDIR = ../inc

# define a location of library
LIBDIR = ../lib

# define compile time flags
CFLAGS = -Wall -g -I$(IDIR)

# define library relared fags
LFLAGS = -L/home/prupala/tech-study/Technical-study/userspace/2.Library/sharedlib-separate-folders/lib

# define library related extra flags
EXTRA_LFALGS = -Wl,-rpath=/home/prupala/tech-study/Technical-study/userspace/2.Library/sharedlib-separate-folders/lib

# define a library to link
LIBS = -lshared

# define name of executable
TARGET = sharedlib-test

# define library dependency
LIBDEP = libshared.so

# define source files
SRC = main.c

# define object files
OBJS = $(SRC:.c=.o)

# define required variables
RM = rm -rf
CD = cd

all: $(TARGET)

$(LIBDEP):
	$(CD) $(LIBDIR); $(MAKE)

$(TARGET): $(LIBDEP) $(IDIR)
	$(CC) $(CFLAGS) -o $@ $(SRC) $(LFLAGS) $(LIBS) $(EXTRA_LFALGS)

clean:
	$(RM) $(OBJS) $(TARGET)
	$(CD) $(LIBDIR); $(MAKE) clean
